### PR TITLE
Enable the arrays to be marked as "required"

### PR DESCRIPTION
**Pull request by crumblix**
### Reasons for making this change

New feature:

Enable the arrays to be marked as "required".  Meaning that the user must select "at least one" option from the list.

This references the array part of ticket:
https://github.com/mozilla-services/react-jsonschema-form/issues/411

### Checklist

* [x ] **I'm updating documentation**
  - [ ] I've checked the rendering of the Markdown text I've added
  - [ ] If I'm adding a new section, I've updated the Table of Content
* [x ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [x ] I've updated docs if needed
* [x ] **I'm adding a new feature**
  - [x ] I've updated the playground with an example use of the feature

Test performed.  I've set each of the items in the arrays section of the playground to required and get no errors or warnings ... other than the expected validation message due to an element being "required"

```jsx
  "required": [
    "listOfStrings",
    "multipleChoicesList",
    "fixedItemsList",
    "nestedList",
    "unorderable",
    "unremovable",
    "noToolbar",
    "fixedNoToolbar"
  ],
```

### CODE REVIEW

**Comment by n1k0** [comment]
It seems people are agreeing on this behavior and want to see it implemented in the lib, see ongoing dicussion in #402.

I'd like to make them happy and land this along #410, would you be willing to post your modifications as a single consistent PR so it's easier to review and discuss the implementation? Thanks!

**Comment by crumblix** [comment]
Sure thing!  Happy to :)

I've got a busy day ahead but I'll try and get to it tonight if that's OK?

Just so as I've got what you want straight, I'll merge my changes for #410 into this PR?

**Comment by n1k0** [comment]
> I've got a busy day ahead but I'll try and get to it tonight if that's OK?

No rush, I'm going to bed (ahh the joys of timezones) ;)

> Just so as I've got what you want straight, I'll merge my changes for #410 into this PR?

Works for me.

**Comment by crumblix** [comment]
This has now all been wrapped up in a new PR #442.   This PR can be closed.

**Pull request closed without merging**
