### PR TITLE
Make BaseInput overridable

### PR DESCRIPTION
**Pull request by olzraiti**
### Reasons for making this change

All the other components in registry fields & widgets are overridable. BaseInput shouldn't be an exception. Customizing BaseInput is useful e.g. for propagating changes only on text input blur.

BTW there is something wrong with the npm commit hook - after pushing the first commit I noticed that some files were prettified after pushing, but the prettified changes were in git staging and weren't pushed. 

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've checked the rendering of the Markdown text I've added
  - [ ] If I'm adding a new section, I've updated the Table of Content
* [x] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated docs if needed
  - [x] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by glasserc** [comment]
Looks OK to me. Can we add a brief note to the documentation explaining that this is possible and why you might want to do this?

Regarding the commit hook, I've never heard of it accidentally not committing stuff. I'm more familiar with husky committing too much stuff, as in https://github.com/Kinto/kinto-admin/issues/419.

**Comment by Chun-Yang** [comment]
Can we change 'BaseInput' to 'BaseInputWidget' to make it consistent?
Since BaseInput is not an open API, the name change should not affect anyone anyway.

**Comment by glasserc** [comment]
That sounds OK to me.

**Comment by olzraiti** [comment]
> Can we change 'BaseInput' to 'BaseInputWidget' to make it consistent?
> Since BaseInput is not an open API, the name change should not affect anyone anyway.

On the other hand, excluding the "Widget" part in the component/file name communicates that it's not a widget. It isn't a widget because you can't use `BaseInput` with `ui:widget` in `uiSchema`. Maybe we should move it away from `widgets` directory or use an underscore in the file name, but I think it's OK like it is now.

**Comment by glasserc** [comment]
Thanks!

**Comment by anlesk** [comment]
Hi guys,

I've just updated to the latest version of react-jsonschema-form and faced the issue with Jest snapshot tests. We have a custom widget that is actually a wrapper for original TextWidget.
With that PR being merged to master, snapshot test of custom widget is starting to fail with "unable to read property widgets of undefined". 

Shouldn't default registry be defined as a default prop for TextWidget? I found a workaround providing registry as a property for custom widget but that looks like a hack to me.
```
import { getDefaultRegistry } from 'react-jsonschema-form/lib/utils';
<CustomTextWidget  registry={getDefaultRegistry()} />
```

Please share your thoughts.

**Comment by olzraiti** [comment]
The `registry` property must be passed to child fields/widgets always. If `BaseInput` doesn't receive `registry`, then it's likely that some of your custom fields/widgets doesn't pass the `registry` property properly.

We can't use the default registry as a default, because then the custom fields/widgets wouldn't be used.

**Comment by anlesk** [comment]
@olzraiti, thanks for the response!

Shouldn't we define registry as a required propType than?

**Comment by olzraiti** [comment]
@anlesk Yes, good idea. Feel free to open a pull request for that :)

**Pull request merged**
