### PR TITLE
Add new number input for type number

### LINKED ISSUE #966: Default widget for number fields
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

Default widget for numbers seems to be text fields.

### Steps to Reproduce
```js
const Form = JSONSchemaForm.default;
const schema = {
  title: "react-jsonschema-form demo",
  type: "object",
  properties: {
  	rate: {type: "number"},
    percent: {type: "number"}
  }
};
const uiSchema = {
  percent: {
    "ui:widget": "range"
  }
};

ReactDOM.render(<Form schema={schema} uiSchema={uiSchema}/>, 
             document.getElementById("main"));
```

#### Expected behavior

I would expect the serialized value to be an integer or float

#### Actual behavior

Currently the value is quoted as string

### PR DESCRIPTION
**Pull request by leplatrem**
### Reasons for making this change

When schema has `type: number`, we should use a `type=number` otherwise with a text widget the serialized value is a string.

Fixes #966 

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've checked the rendering of the Markdown text I've added
  - [ ] If I'm adding a new section, I've updated the Table of Content
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [x] I've updated docs if needed
  - [x] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by glasserc** [comment]
Refs #958, #674. When you write "the serialized value is a string", what does "serialized" mean? Is the value in `formData` a string, even when the entered value is a number?

**Comment by leplatrem** [comment]
> When you write "the serialized value is a string", what does "serialized" mean? Is the value in formData a string, even when the entered value is a number?

Yes, the field value in the data passed to `onSubmit` is a string even if the entered value is a number. 

The original issue is this https://bugzilla.mozilla.org/show_bug.cgi?id=1468878

**Comment by glasserc** [comment]
This is a duplicate of #674. Specifically, the number being entered is `1.0`, which cannot be represented as a JavaScript number. I don't see how changing the type of the input field will fix the issue.

**Comment by leplatrem** [comment]
> This is a duplicate of #674

Ok closing then.

**Pull request closed without merging**
