### PR TITLE
Attempt at providing memoization for stateless components.

### PR DESCRIPTION
**Pull request by n1k0**
This is an experimental attempt at addressing #147 by memoizing stateless component widgets, hopefully for faster rerenderings.

### CODE REVIEW

**Comment by kaihendry** [comment]
Not sure I can confidently test that 
http://s3.jptdev.com/2016-04-20/147scm.html is any faster than http://s3.jptdev.com/2016-04-20/147.html :confused: 

http://s3.jptdev.com/2016-04-20/react-jsonschema-form.js is the library built from the "stateless-component-memoization" branch.

**Comment by n1k0** [comment]
New version with all field stateless comps memoized as well. Feedback still warmly welcome.

**Comment by n1k0** [comment]
I just obtained great perf boost in 7e54422bb5faf35cd283f30badcfd2e3d0e8326c, which has nothing to do with stateless components memoization at all, but rather with the way we were waiting for setState to have finished to propagate state to parent components.

@kaihendry sorry to bother you again, but could you please confirm this actually improves the perf situation for you? thanks in advance.

**Comment by n1k0** [comment]
Superseded by #153.

**Pull request closed without merging**
