### PR TITLE
Pass empty title to TitleField instead of name

### PR DESCRIPTION
**Pull request by olzraiti**
Currently if you put `""` as a title in the schema, it won't be used because `"" == false`.

This pull request makes it possible to give an empty title to a jsonschema field without it being overwritten with the field's name.

### CODE REVIEW

**Comment by n1k0** [comment]
Could you please add a test? Thanks.

**Comment by olzraiti** [comment]
Yes, hopefully next week.

**Comment by olzraiti** [comment]
Found the time for this today after all. :-)

**Comment by n1k0** [comment]
r+, thanks a lot for your contribution.

**Comment by n1k0** [comment]
Released in [v0.41.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.41.0).

**Comment by awakentwice** [comment]
What if I don't want use label at field?

**Pull request merged**
