### PR TITLE
An example of moving required styling to classes so can be controlled with css

### PR DESCRIPTION
**Pull request by kav**
No docs update, just want to show the code changes for the jsfiddle I listed in #275

### CODE REVIEW

**Comment by mplis-jetsetter** [comment]
I'd definitely like to see some way to allow library users to style this kind of stuff through CSS. I know this is just an example so maybe you've considered this, but I think there should still be some default styling. This PR would force every user of this library to add some CSS to get any kind of required/optional styling. Also, should there also be a class like `control-label-optional` so you can target those elements? Otherwise, it seems like you'd have to use some kind of negative selector if you wanted to just denote the optional elements.

**Comment by kav** [comment]
100% agree

**Comment by n1k0** [comment]
Accessibility considerations apart (which are probably a concern here though), we'll eventually move towards a field template system like suggested in https://github.com/mozilla-services/react-jsonschema-form/issues/275#issuecomment-231948348; that way people will have a way to provide their very own semantics (like what this patch suggests), while we provide accessible defaults.

**Comment by kav** [comment]
Seems reasonable though I'd argue some more detailed classing and hinting as above are far more accessible than * at the end of the label so I'd still encourage for something more like that as the default. Happy to address @mplis-jetsetter's concerns if you'd like.

**Comment by n1k0** [comment]
Templates have landed in #304 and are the recommended way to alter the HTML field semantics.

**Pull request closed without merging**
