### PR TITLE
Generate code coverage reports using nyc

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Change-type: patch
Signed-off-by: Lucian <lucian.buzzo@gmail.com>

### Reasons for making this change

Having code coverage reports is useful for detecting uncovered code paths.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've [checked the rendering](https://react-jsonschema-form.readthedocs.io/en/latest/#contributing) of the Markdown text I've added
* [ ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated [docs](https://react-jsonschema-form.readthedocs.io/) if needed
  - [ ] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by epicfaace** [comment]
Looks good, but I think we should find a way to publish the reports. Could we maybe integrate travis ci and nyc? Or, maybe it's better to use a tool such as [code climate](https://codeclimate.com/oss/) instead so it can easily be published?

**Comment by epicfaace** [comment]
> How much does this slow down the tests ?
> 
> Can you measure time before / after ?
> 
> If it slows down significantly, I would suggest to create a special command in package.json for this (npm test-coverage for example)

Yeah, I think making a special command is the right way to go, as one wouldn't need to create code coverage reports each time one runs the tests, right?

**Comment by LucianBuzzo** [comment]
@edi9999 @epicfaace I ran some tests locally and saw, on average, a time increase of ~5s. Whilst this is not a huge increase it is proportionally significant when you consider that the average test run without coverage is only 10s. I'll add a separate command for running the coverage report. 
Code climate looks interesting, how about we open a new issue about integrating it into this project?

**Comment by epicfaace** [comment]
Looks good; let's do that.

**Pull request merged**
