### PR TITLE
[Experiment] Ref #80: Add support for enumNames to boolean widgets.

### PR DESCRIPTION
**Pull request by n1k0**
WiP, experimental, do not merge. Refs #80.

Feedback=? @chmac

### CODE REVIEW

**Comment by chmac** [comment]
Can't really comment on the code, looks good to me...

The docs might be clearer with an example. Something like this?

> To set the labels for a boolean field, instead of using `true` and `false` you can set `enumNames` in your schema. Note that `enumNames` belongs in your `schema`, not the `ui:schema` and the order is `[true, false]`.

One minor thought, will the `enumNames` keyword be valid on fields of type `boolean`? My JSON schema fu is not strong enough to answer that definitively, and I couldn't find anything in the `enumNames` proposal to suggest either way...

**Comment by n1k0** [comment]
> One minor thought, will the enumNames keyword be valid on fields of type boolean?

It's quite surprisingly "valid" when tested on http://jsonschemalint.com/draft4/, though I think we're probably bending the spec a little here.

I may be spend a little while figuring out how hard would be to add support for proper uiSchema widget options, which would sound definitely much cleaner to me.

**Comment by chmac** [comment]
@n1k0 Could it be that arbitrary keys are allowed, but once v5 gets finalised the key might be only allowed in some situations? Anyway, if it works now, great, no harm, no foul!

**Comment by n1k0** [comment]
Yeah, and my main concern is that uiSchema introduces a nice way of separating the data model from its presentation, and moving the labels definition there seems most definitely the right thing to do.

I'll probably implement the uiSchema widget option object thing.

**Comment by n1k0** [comment]
Okay, I just had a look at the required changes to properly support widget options, it's too much work for what we're trying to achieve here. I think I'm gonna land this for now, and we'll revisit the way we handle widget options when we'll need them.

**Comment by chmac** [comment]
Awesome, thanks a lot @n1k0. At this rate, I'll soon be your biggest fan! :-)

If you're ever passing by Berlin, beers are on @superlumen. :-)

**Comment by n1k0** [comment]
Haha, noted! Cheers.

**Comment by hiitskiran** [comment]
I know this is a very old post but, along with enumNames, can you also add support for enum for Boolean so we can specify in our schema what are the saved values? without enum support we have to transform the data back and forth from form so the values are saved as Y/N instead of true/false.

              "myCheckbox": {
                "type": "boolean",
                "enum" : ["Y","N"],
                "enumNames": ["Yes","No"],
                "title": "Enabled"
              },

**Comment by epicfaace** [comment]
@hiitskiran in that case, you should use a string type:

```
          "myCheckbox": {
            "type": "string",
            "enum" : ["Y","N"],
            "enumNames": ["Yes","No"],
            "title": "Enabled"
          },
```

**Comment by hiitskiran** [comment]
> @hiitskiran in that case, you should use a string type:
> 
> ```
>           "myCheckbox": {
>             "type": "string",
>             "enum" : ["Y","N"],
>             "enumNames": ["Yes","No"],
>             "title": "Enabled"
>           },
> ```

but we want to present in UI as a check box and checked value to store it as "Y" and unchecked "N"

**Comment by epicfaace** [comment]
It might be best to make a custom widget in that case. otherwise, #1651 might be related to something you would need.

**Comment by hiitskiran** [comment]
thanks Ashwin, but looking at BooleanField.js, it does look like taking "enum" from schema, but wonder why my enums are not taking into account and the values are still stored as true/false instead of enum values Y/N

    enumOptions = (0, _utils.optionsList)({
      "enum": schema["enum"] || [true, false],
      enumNames: schema.enumNames || (schema["enum"] && schema["enum"][0] === false ? ["no", "yes"] : ["yes", "no"])
    });

**Pull request merged**
