### PR TITLE
fix(SchemaField): correctly change stateful error class name string

### PR DESCRIPTION
**Pull request by elisechant**
Fixes https://github.com/mozilla-services/react-jsonschema-form/issues/501

### CODE REVIEW

**Comment by glasserc** [comment]
Thanks for your contribution! I think a couple of tests need to be updated too, although I can't see the Travis error output for some reason.

**Comment by glasserc** [comment]
I just noticed that the version of Bootstrap we use is 3.3.6, and in that version, `.has-error` is correct. See http://getbootstrap.com/css/#forms-control-validation.

**Comment by elisechant** [comment]
@glasserc sorry, adding both `has-error` as well as `has-danger` to support Bootstrap 3 and 4. How do you feel about that?

**Comment by elisechant** [comment]
tests passing for me: 

screen shot 2017-03-02 at 12 39 51 pm

I can't see any specific test for that piece of code.

**Comment by n1k0** [comment]
Existing tests for error handling are written matching the `.field-error` selector, so we're safe here. Merging.

**Comment by glasserc** [comment]
Related to #299.

**Comment by n1k0** [comment]
Released in [v0.44.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.44.0).

**Pull request merged**
