### PR TITLE
Onfocus support

### PR DESCRIPTION
**Pull request by mauriciominella**
### Reasons for making this change

I'm currently developing a JSON Based Configuration editor, where I'll have a split screen where the Form and the raw JSON will be displayed side-by-side. One of the requirements is to highlight the correspondent field on the raw JSON split as soon a field is focused on the form. Currently only onBlur event is supported, so, I've added onFocus support.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've checked the rendering of the Markdown text I've added
  - [ ] If I'm adding a new section, I've updated the Table of Content
* [ ] **I'm adding or updating code**
  - [X] I've added and/or updated tests
  - [X] I've updated docs if needed
  - [X] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [X] **I'm adding a new feature**
  - [X] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by n1k0** [comment]
LGTM. Please just remove the added `package-lock.json`, we don't want to version this file with this project.

**Comment by mauriciominella** [comment]
@n1k0 Thanks for the heads up. I've just removed the file as requested.

**Comment by n1k0** [comment]
Thanks!

**Comment by theengineear** [comment]
@n1k0 I was hoping to use this onFocus support in a project, any chance a new release is slated soon?

**Comment by glasserc** [comment]
Released in v0.50.0.

**Pull request merged**
