### PR TITLE
Add sharing capability to the Playground.

### PR DESCRIPTION
**Pull request by n1k0**
This patch adds sharing capabilities to the Playground. It adds a new *Share* button which when pressed generates a link people can send each others to retrieve the form setup. This will be especially useful to report bugs.

### CODE REVIEW

**Comment by n1k0** [comment]
I've deployed the patch to gh-pages for easier review & QA. Here's [an example](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmb28iOiJmb3JtRGF0YSBhcmUgc2hhcmVkIHRvbyJ9LCJzY2hlbWEiOnsidGl0bGUiOiJUaGlzIGlzIGEgc2hhcmVkIGN1c3RvbSBmb3JtIiwiZGVzY3JpcHRpb24iOiJJIHRoaW5rIGl0J3MgdXNlZnVsIGZvciBwZW9wbGUgdG8gcmVwb3J0IGJ1Z3MuIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiZm9vIjp7InRpdGxlIjoiQ3VzdG9taXplZCBmaWVsZCBwcm9wZXJ0aWVzIGFyZSBzdXBwb3J0ZWQiLCJ0eXBlIjoic3RyaW5nIn19fSwidWlTY2hlbWEiOnsiZm9vIjp7InVpOndpZGdldCI6InRleHRhcmVhIn19fQ==).

**Comment by revolunet** [comment]
nice !
nitpicking here, but what about a direct "copy link" with clipboard support ?

**Comment by n1k0** [comment]
> nitpicking here, but what about a direct "copy link" with clipboard support ?
Awesome idea, will do.

**Comment by revolunet** [comment]
you just saved the world hundreds clicks a day, thanks ! 👌

**Pull request merged**
