### PR TITLE
Remove functions from props during shouldComponentUpdate

### PR DESCRIPTION
**Pull request by mplis-jetsetter**

### CODE REVIEW

**Comment by Natim** [comment]
Could you give a little bit of a rationate about that PR?

**Comment by Natim** [comment]
Is it related to #255 discussions?

**Comment by n1k0** [comment]
> Is it related to #255 discussions?

Yes

**Comment by n1k0** [comment]
I've just deployed your patch to [gh-pages](https://github.com/mozilla-services/react-jsonschema-form). Sadly I couldn't spot any specific perf improvements... is there any specific to inspect and test manually? I've use Chrome CPU recording and timeline tabs but I'm not a spcialist, so hints are welcome.

**Comment by mplis-jetsetter** [comment]
You're sure it's deployed to [gh-pages]()? When I run this branch locally and am on the Nested tab, I can turn on "Trace React updates" when using the React Developer Tools in Chrome and see that the items in the Tasks array are not being rerendered, [but I'm not seeing the same results when I do the same thing in the playground](http://imgur.com/a/bKfif).

**Comment by n1k0** [comment]
> You're sure it's deployed to gh-pages?

It's not deployed there anymore as I've released v0.35.1 in the meanwhile, and had to deploy the updated version of the playground. I'll redeploy the patch.

**Comment by n1k0** [comment]
> I can turn on "Trace React updates" when using the React Developer Tools in Chrome and see that the items in the Tasks array are not being rerendered

That means we have a mutated function reference passed down to child components there. I'm now pretty convinced it's [`onChangeForIndex`](https://github.com/mozilla-services/react-jsonschema-form/blob/37eb321873729d43d4d0cbbd51144048edf15d4e/src/components/fields/ArrayField.js#L108-L116), which is an higher order function (a function returning a function). Because:

```js
> function foo(){return () => {}}
undefined
> foo() === foo()
false
```

**Comment by mplis-jetsetter** [comment]
> I'm now pretty convinced it's onChangeForIndex, onPropertyChange and similarily shaped functions

Oh interesting. It looks like changing the structure of those functions does prevent some of the unnecessary rerendering I was seeing before. I've been unsuccessfully fighting with `npm link` to try to test out those changes in my app (any tips?), but it does at least seem promising.

**Comment by n1k0** [comment]
> It looks like changing the structure of those functions does prevent some of the unnecessary rerendering I was seeing before

What did you do? I'm pulling my hair out trying to figure out how to pass down the right comparable function for these with no luck so far... Maybe your approach is the way to go after all.

>  I've been unsuccessfully fighting with npm link to try to test out those changes in my app (any tips?)

I never managed to achieve that, but I'm interested :)

**Comment by n1k0** [comment]
Care to elaborate why closing this? :)

**Comment by mplis-jetsetter** [comment]
Yeah sorry that was my bad. I was messing with my fork and accidentally closed this. I can resubmit it if you want.

> What did you do? I'm pulling my hair out trying to figure out how to pass down the right comparable functions for these with no luck so far.

I didn't do anything fancy. I literally just pulled the returned function out and put it on the class like this:

```
_onChangeForIndex = (value) => {
  this.asyncSetState({
    items: this.state.items.map((item, i) => {
      return index === i ? value : item;
    })
  });
}

onChangeForIndex = (index) => {
  return this._onChangeForIndex;
};
```

I was just playing around and wanted to see if it made any difference, [which it did](http://imgur.com/YWTSRy4), though there's still some unnecessary rerendering.

**Comment by n1k0** [comment]
> I was just playing around and wanted to see if it made any difference, which it did

Well maybe there's some perf improvement but this code doesn't work for actually updating the state :) you need to pass `index` to `_onChangeForIndex`, and that's precisely where it gets tricky...

**Comment by mplis-jetsetter** [comment]
Ha wow, I obviously wasn't paying close enough attention when I made that change. I wonder why I didn't get a bunch of `ReferenceError`s saying that `index is not defined`.

I had assumed that my approach was going to be a little too hacky, but if you're thinking it might be the way to go, should I resubmit the PR? I might actually have to submit a new one instead of reopening this one.

**Comment by n1k0** [comment]
Yeah please resubmit it. I've seen other people removing functions from objects before comparing them in `shouldComponentUpdate`, and after thinking about it for a while now renders should never be conditional to the function references we pass as props in this project. Also, I like that it's a simple and fast approach :)

**Comment by mplis-jetsetter** [comment]
Resubmitted the PR in #261

**Pull request closed without merging**
