### PR TITLE
minimum and maximum props are not passed to UpDownWidget and RangeWidget

### PR DESCRIPTION
**Pull request by pabloen**
… when value === 0

### CODE REVIEW

**Comment by n1k0** [comment]
Thanks! Would you mind adding a test? :)

**Comment by pabloen** [comment]
Sure! here they are.
Btw, found and solved the same issue for RangeWidget.

**Comment by n1k0** [comment]
Awesome, thanks! Also, I'm realizing the `rangeSpec` functions are the same, would you mind factorizing them out in the `utils` module? That'd be just great :)

**Comment by pabloen** [comment]
Sure thing, glad to help!
This library have served me well.

**Comment by n1k0** [comment]
Thank you!

**Comment by n1k0** [comment]
Released in [v0.41.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.41.0).

**Pull request merged**
