### PR TITLE
Introducing FileWidget

### PR DESCRIPTION
**Pull request by n1k0**
This is an ongoing experimentation around #192.

### CODE REVIEW

**Comment by Natim** [comment]
Note that kinto-attachment doesn't supports multiple files per records just yet.

**Comment by n1k0** [comment]
This lib should remain fully agnostic from Kinto anyway.

**Comment by Natim** [comment]
> This lib should remain fully agnostic from Kinto anyway.

Yes sure.

**Comment by Natim** [comment]
This is now ready :dancer:

**Pull request merged**
