### PR TITLE
Adds prop topBar for hiding display of Topbar

### PR DESCRIPTION
**Pull request by garywong89**
I added a property topBar to allow the toggle of the Error message bar to be hidden along with some test. [Issue 251](https://github.com/mozilla-services/react-jsonschema-form/issues/251) had also mentioned having the option of setting the top bar hidden.

### CODE REVIEW

**Comment by n1k0** [comment]
LGTM. I'm not too sure about the `topBar` name; how about just `errorList`?

Also this would need some documentation in the README.

**Comment by n1k0** [comment]
Thanks, this is a great patch. Much appreciated :+1:

**Comment by garywong89** [comment]
No problem. Glad to able to contribute.

**Comment by n1k0** [comment]
Released in [v0.38.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.38.0).

**Pull request merged**
