### PR TITLE
Missing prototype in CheckboxesWidget.js

### PR DESCRIPTION
**Pull request by crumblix**
### Reasons for making this change

Missing prototype in CheckboxesWidget.js

Referencing issue:
https://github.com/mozilla-services/react-jsonschema-form/issues/413

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've checked the rendering of the Markdown text I've added
  - [ ] If I'm adding a new section, I've updated the Table of Content
* [x ] **I'm adding or updating code**
  - [ ] I've added and/or updated tests
  - [ ] I've updated docs if needed
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by crumblix** [comment]
OK ... that didn't work the way I wanted .... I only want one of those patches in this PR :(

**Comment by crumblix** [comment]
Also ... that failed auto-test was a syntax error fixed in a later commit.  Obviously this system requires each individual commit to be good, rather than the set?

Anyway really I just wanted 	c7a7b4a in this PR.  For the life of my though I can't find how to select/deselect the commits I want in my PR ... I'll keep looking and reading.

Sorry for the confusion, but I will get better at this!

**Comment by n1k0** [comment]
Hey now worries, things always have to be learned at some point ;)

Try to learn about rebasing, this is exactly what you need here; the idea would be to force push your branch rebased with your single commit here. There are a lot of good tutos out there about this!

**Comment by crumblix** [comment]
Thanks Nicholas ... will do! :)

**Comment by n1k0** [comment]
Fixed by #416

**Pull request closed without merging**
