### PR TITLE
Fixes #250: Add support for custom widget options.

### LINKED ISSUE #250: Add support for custom widget options
We should add support for options to custom widgets, so these could access them as props.

```js
const CustomWidget(props) {
  const {value, onChange, options} = props;
  return <div className={options.className} />;
}

const uiSchema = {
  "ui:widget": {
    widget: CustomWidget, 
    options: {
      className: "toto"
    }
  }
};
```

### PR DESCRIPTION
**Pull request by n1k0**
Refs #250, WiP.

### CODE REVIEW

**Comment by n1k0** [comment]
When suddenly you read this in the custom widget docs:

> - `options`: The list of options for `enum` fields;

We need to find a better prop name; `config`? `widgetOptions`? `context`? `params`?

**Comment by olzraiti** [comment]
We have used 'ui:options' as options prop name for custom schema fields' uiSchemas.

**Comment by n1k0** [comment]
> We have used 'ui:options' as options prop name for custom schema fields' uiSchemas.

For custom *fields* that's a good way to go, but this patch is about provising options to *custom widgets* :)

**Comment by n1k0** [comment]
Paired with @magopian.

**Pull request merged**
