### PR TITLE
FieldSet component w/ tests

### PR DESCRIPTION
**Pull request by zbyte64**
New FieldSet component which acts like Form but:
* no onSubmit
* no onError
* no default submit button
* renders as fieldset tag

Should this also be exposed as part of index.js?

### CODE REVIEW

**Comment by n1k0** [comment]
I'm surprised the `Form` component doesn't leverage this new `Fieldset` component at all... I'm not comfortable duplicating the shared logic here.

As an illustration, we recently landed support for error contextualization at the field level in #85 and your patch doesn't conflict at all, while it should definitely use the new feature. Another obvious illustration is the duplicated tests.

Could you find a way to share the common logic bits between the two components?

**Comment by zbyte64** [comment]
Ended up making `Form` inherit from `FieldSet`. A couple things I am uncertain about:
* Should `FieldSet` include `renderErrors`; FieldSet does not call it
* Maybe both `FieldSet` and `Form` should extend a common class instead of `Form` extending `FieldSet`; not sure what it would be called

**Comment by n1k0** [comment]
> Ended up making Form inherit from FieldSet. 

I was more expecting composition here. How about something like:

```js
class Form extends Component {
  constructor(props) {
    ...
  }

  render() {
    return (
      <form onSubmit={...}>
        <FieldSet {...props} />
      </form>
    );
  }
}
```

**Comment by zbyte64** [comment]
Would that mean `Form` maintains its own `formData` state or would it just use ref (ie this.refs.fieldset.state) when someone triggers `onSubmit`?

**Comment by n1k0** [comment]
I never worked with refs, so I don't know, but if it works like you suggest it does, why not! Otherwise, replicating state is probably unavoidable.

**Pull request closed without merging**
