### PR TITLE
Key-value pair in additional properties retains order when edited

### PR DESCRIPTION
**Pull request by aerfio**
### Reasons for making this change

When you change key it shows on the bottom of the list, instead of keeping its place, keeping the order of key-value pairs.

If this is related to existing tickets, include links to them as well.

### Checklist

* [ ] **I'm updating documentation**
  - [ ] I've checked the rendering of the Markdown text I've added
  - [ ] If I'm adding a new section, I've updated the Table of Content
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [ ] I've updated docs if needed
  - [x] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [ ] **I'm adding a new feature**
  - [ ] I've updated the playground with an example use of the feature

Solves two things of #1099

### CODE REVIEW

**Comment by aerfio** [comment]
Hey guys, any comment on this?

**Comment by edi9999** [comment]
Can you add a test case in the same form as https://github.com/mozilla-services/react-jsonschema-form/blob/master/test/ObjectField_test.js#L582 that fails before your patch, and succeeds afterwards ?

**Comment by aerfio** [comment]
@edi9999 Done

**Comment by edi9999** [comment]
Great , merging !

**Comment by aerfio** [comment]
@edi9999 When do you guys plan to realease 1.0.7? Do you have it scheduled? :d

**Pull request merged**
