### PR TITLE
Added possibility to change title and description by ui:schema.

### PR DESCRIPTION
**Pull request by stepek**
### Reasons for making this change
Added possibility to change title and description of field using ui:schema.

### Checklist

* [x] **I'm updating documentation**
  - [x] I've checked the rendering of the Markdown text I've added
  - [x] If I'm adding a new section, I've updated the Table of Content
* [x] **I'm adding or updating code**
  - [x] I've added and/or updated tests
  - [x] I've updated docs if needed
  - [x] I've run `npm run cs-format` on my branch to conform my code to [prettier](https://github.com/prettier/prettier) coding style
* [x] **I'm adding a new feature**
  - [x] I've updated the playground with an example use of the feature

### CODE REVIEW

**Comment by n1k0** [comment]
Title and description are part of the JSONSchema spec, why would one want to duplicate the source for these information?

**Comment by stepek** [comment]
This is no duplication of data, because main purpose is add possibility to change title and description, (for e.g. locale settings); if ui:title is not setted, user will see jsonschema title.

**Comment by n1k0** [comment]
Ok I could see use cases for people using generated schemas or things like that. Could you please add tests and update docs for this patch? Thanks.

**Comment by stepek** [comment]
@n1k0 Done

**Pull request merged**
